# Config file for automatic testing at travis-ci.org
dist: xenial

language: python

os:
  - linux

matrix:
  include:
    - name: "Python 3.7"
      python: 3.7
    - name: "Python 3.6"
      python: 3.6

cache:
  - pip
  - directories: tests/data

notifications:
  email: false

install:
  - pip install --quiet .[test,notebooks]

script:
  - flake8
  - black --check .
  - python setup.py check --restructuredtext
  - coverage run setup.py test

after_success:
  - codecov
  - pip list

branches:
  only:
  - master
