name: Test (Linux, CUDA)

on:
  push:
    branches:
      [main, 0.15.x, 0.16.x, 0.17.x, 0.18.x, 0.19.x, 0.20.x, 1.0.x, 1.1.x]
  pull_request:
    branches:
      [main, 0.15.x, 0.16.x, 0.17.x, 0.18.x, 0.19.x, 0.20.x, 1.0.x, 1.1.x]
  schedule:
    - cron: "0 10 * * *" # runs at 10:00 UTC -> 03:00 PST every day
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: [self-hosted, Linux, X64, CUDA]
    defaults:
      run:
        shell: bash -e {0} # -e to fail on error

    strategy:
      fail-fast: false
      matrix:
        python: ["3.11"]
        cuda: ["11"]

    container:
      image: martinkim0/scvi-tools:py${{ matrix.python }}-cu${{ matrix.cuda }}-base
      options: --user root --gpus all

    environment:
      name: approved_test

    name: ${{ matrix.name }} Python ${{ matrix.python }}

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
          cache-dependency-path: "**/pyproject.toml"

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip wheel

      - name: Install dependencies
        run: |
          pip install --pre ".[tests]"

      - name: Test
        env:
          MPLBACKEND: agg
          PLATFORM: ${{ matrix.os }}
          DISPLAY: :42
        run: |
          coverage run -m pytest -v --color=yes --accelerator cuda --devices auto
      - name: Report coverage
        run: |
          coverage report
      - name: Upload coverage
        uses: codecov/codecov-action@v3
